### ISSUE TITLE
Vulnerable Regular Expression

### ISSUE THREAD

**Issue by cristianstaicu** [blakeembrey/no-case#17]
The regular expression in camel-case-upper-regexp.js, used to transform the input string is vulnerable to ReDoS:

The slowdown is moderately low: for 50.000 characters around 2.5 seconds matching time. However, I would still suggest one of the following: 
- remove the regex,
- anchor the regex,
- limit the number of characters that can be matched by the repetition,
- limit the input size.

If needed, I can provide an actual example showing the slowdown.

**Comment by blakeembrey** [comment]
Thanks for the catch! It should be any easy fix by removing the repeating parameter.
