### ISSUE TITLE
Support of '@' character

### ISSUE THREAD

**Issue by 4nduril** [blakeembrey/no-case#20]
Hello,
I just wondered if it would be against the idea of this tool to support the `@` character in strings. 

My case was using [param-case](http://www.github.com/blakeembrey/param-case) in a Vue-JS-App where I have HTML attributes beginning with an `@`. So, when I tried to convert `@myAttribute` to `@my-attribute` I got ` my-attribute` instead.

**Comment by alukach** [comment]
Agreed, along with an `'*'`.

**Comment by blakeembrey** [comment]
Discussion can be moved to https://github.com/blakeembrey/change-case, this repo will be deleted in favor of the mono-repo.
