### ISSUE TITLE
reduce regex file size?

### ISSUE THREAD

**Issue by ianstormtaylor** [blakeembrey/no-case#24]
I'm potentially interested in deprecating my `to-case` library, since I'd rather consolidate. But the camelcase regexes in this library make it really large:

[![image](https://user-images.githubusercontent.com/311752/53998357-3f514780-40f4-11e9-9be7-d512fd6a5418.png)](https://bundlephobia.com/result?p=no-case)

Looking at the regexes, it looks like they could be optimized a lot, but I'm not an expert. For example, ranges like:

```
\uA640
\uA641
\uA642
\uA643
\uA644
\uA645
\uA646
\uA647
\uA648
\uA649
\uA64A
\uA64B
\uA64C
\uA64D
\uA64E
\uA64F
\uA650
\uA651
\uA652
\uA653
\uA654
\uA655
\uA656
\uA657
\uA658
\uA659
\uA65A
\uA65B
\uA65C
\uA65D
\uA65E
\uA65F
\uA660
\uA661
\uA662
\uA663
\uA664
\uA665
\uA666
\uA667
\uA668
\uA669
\uA66A
\uA66B
\uA66C
\uA66D
\uA680
\uA681
\uA682
\uA683
\uA684
\uA685
\uA686
\uA687
\uA688
\uA689
\uA68A
\uA68B
\uA68C
\uA68D
\uA68E
\uA68F
\uA690
\uA691
\uA692
\uA693
\uA694
\uA695
\uA696
\uA697
\uA698
\uA699
\uA69A
\uA69B
```

Could be turned into:

```
\uA640-\uA69B
```

And then the regexes themselves might contain a bunch of duplicate ranges. If they were constructed from strings, maybe they could be declared once instead of multiple times?

**Comment by ianstormtaylor** [comment]
False alarm on the "a lot" for the range collapsing optimization sadly. That range example doesn't actually exist in the source, since I made a mistake extracting the unicode values from that regex the first time I did it. There are a few spots that the ranges could be further collapsed, but not as many as I'd hoped.

The duplication itself I feel like is solved already by GZIP, so that's not an issue. Although the regexes aren't necessarily in the same order, so that could be preventing a small amount of GZIPing.

I'll check out both optimizations and see what their results are.

If they aren't meaningful... it's kind of unfortunate that this library can't be smaller.

**Comment by ianstormtaylor** [comment]
Here's a diff showing where the regexes can be collapsed: https://www.diffchecker.com/eejOAK6X

**Comment by blakeembrey** [comment]
@ianstormtaylor I think you're right that this could be done more efficiently. I won't get to this immediately, but think I could take a look and improve the pattern in the next month or so. I'd also consider deprecating the usage of the module with this built in and use support ASCII by default - allow this via configuration only out of the normal path. E.g. separate module or override the split regex yourself.

**Comment by ianstormtaylor** [comment]
@blakeembrey that would be awesome! Yeah it’s probably the case that no amount of optimization is going to make up for their size, so having it as a choice could be a good way to go. 

Let me know if/when you do and I’d be happy at that point to deprecate my set in favor of the smaller one.

**Comment by blakeembrey** [comment]
I've moved this to a mono-repo and reduced the bundle size: https://github.com/blakeembrey/change-case, https://bundlephobia.com/result?p=change-case@4.0.0. I'll be deleting this repository in favor of the mono-repo, but feel free to re-open an issue over there if I missed anything.
